server:
  port: ${PORT:8080}
  servlet:
    context-path: /sanasa-training-tracker

spring:
  application:
    name: sanasa-training-tracker

  datasource:
    username: postgres
    password: ocIIVuYiNFrTJPaCWJUFElKQuoXSLfcf
    driver-class-name: org.postgresql.Driver
    url: postgresql://postgres:ocIIVuYiNFrTJPaCWJUFElKQuoXSLfcf@maglev.proxy.rlwy.net:16682/railway

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
